version: 0.2

env:
  variables:
    REGISTRY_URI: "710139145643.dkr.ecr.us-east-2.amazonaws.com"
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin $REGISTRY_URI
      - IMAGE_TAG_TYPE="$(echo $CODEBUILD_WEBHOOK_TRIGGER | cut -d'/' -f 1)"
      - IMAGE_TAG_NAME="$(echo $CODEBUILD_WEBHOOK_TRIGGER | cut -d'/' -f 2- | tr / -)"
      - if [ $IMAGE_TAG_TYPE = "tag" ] && [ $IMAGE_TAG_NAME != "${IMAGE_TAG_NAME#release}" ]; then IMAGE_TAG_TYPE=release; fi
      - if [ $IMAGE_TAG_TYPE = "branch" ] && [ $IMAGE_TAG_NAME != "${IMAGE_TAG_NAME#rc-release}" ]; then IMAGE_TAG_TYPE=rc; fi
      - IMAGE_TAG_COMMIT="${IMAGE_TAG_TYPE}-commit-${CODEBUILD_RESOLVED_SOURCE_VERSION}"
      - REPO_URI="${REGISTRY_URI}/pm-trello"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t pm-trello .
      - if [ $IMAGE_TAG_TYPE = "release" ]; then
          docker tag pm-trello:latest $REPO_URI:rc; fi
      - if [ $IMAGE_TAG_TYPE != "branch" ]; then
          docker tag pm-trello:latest $REPO_URI:$IMAGE_TAG_TYPE; fi
      - docker tag pm-trello:latest $REPO_URI:$IMAGE_TAG_NAME
      - docker tag pm-trello:latest $REPO_URI:$IMAGE_TAG_COMMIT
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPO_URI
