version: '3'

services:
  nodejs:
    image: xianbridal/nodejs
    build:
      context: .
      dockerfile: Dockerfile

  nginx:
    depends_on:
      - nodejs
    image: xianbridal/nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "443:443"
