version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "nginx"
          ContainerPort: 443
Hooks:
  - AfterAllowTraffic: "arn:aws:lambda:us-east-1:501045672667:function:xianbridal-create-invalidation"
