version: 0.2

env:
  variables:
    REGISTRY_URI: "501045672667.dkr.ecr.us-east-1.amazonaws.com"
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REGISTRY_URI
      - IMAGE_TAG_TYPE="$(echo $CODEBUILD_WEBHOOK_TRIGGER | cut -d'/' -f 1)"
      - IMAGE_TAG_NAME="$(echo $CODEBUILD_WEBHOOK_TRIGGER | cut -d'/' -f 2- | tr / -)"
      - IMAGE_TAG_COMMIT="${IMAGE_TAG_TYPE}-commit-${CODEBUILD_RESOLVED_SOURCE_VERSION}"
      - REPO_URI_NODEJS="${REGISTRY_URI}/xianbridal-nodejs"
      - REPO_URI_NGINX="${REGISTRY_URI}/xianbridal-nginx"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker images...
      - if [ $IMAGE_TAG_NAME = "master" ]; then
          docker build --build-arg CODEBUILD_BUILD_NUMBER -t nodejs . ;
          docker tag nodejs:latest $REPO_URI_NODEJS:$IMAGE_TAG_NAME;
          docker tag nodejs:latest $REPO_URI_NODEJS:$IMAGE_TAG_COMMIT; fi
      - if [ $IMAGE_TAG_NAME = "nginx" ]; then
          docker build -t nginx -f nginx/Dockerfile . ;
          docker tag nginx:latest $REPO_URI_NGINX:$IMAGE_TAG_NAME;
          docker tag nginx:latest $REPO_URI_NGINX:$IMAGE_TAG_COMMIT; fi
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - if [ $IMAGE_TAG_NAME = "master" ]; then docker push $REPO_URI_NODEJS; fi
      - if [ $IMAGE_TAG_NAME = "nginx" ]; then docker push $REPO_URI_NGINX; fi
